# Auditbeat 9.x Docker Swarm Deployment
# https://www.elastic.co/guide/en/beats/auditbeat/current/auditbeat-overview.html
# Note: Auditd is not supported in Alpine Linux: https://github.com/linuxkit/linuxkit/issues/52

services:

  auditbeat:
    image: docker.elastic.co/beats/auditbeat:${ELASTIC_VERSION:-9.2.4}
    # https://github.com/docker/swarmkit/issues/1951
    hostname: "{{.Node.Hostname}}-auditbeat"
    # Need to override user so we can access the log files
    user: root
    # https://www.elastic.co/guide/en/beats/auditbeat/current/running-on-docker.html#_special_requirements
    # PID and CAP_ADD options require Docker 19.06+ for Swarm mode support
    pid: host
    cap_add:
      - AUDIT_CONTROL
      - AUDIT_READ
    networks:
      - elastic
    configs:
      - source: ab_config
        target: /usr/share/auditbeat/auditbeat.yml
    volumes:
      - auditbeat:/usr/share/auditbeat/data
      - /var/log:/var/log:ro
      # Required for system module
      - /etc/passwd:/hostfs/etc/passwd:ro
      - /etc/group:/hostfs/etc/group:ro
    environment:
      - ELASTICSEARCH_HOST=${ELASTICSEARCH_HOST:-node1}
      - KIBANA_HOST=${KIBANA_HOST:-node1}
      - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME:-elastic}
      - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD:-changeme}
    command: ["--strict.perms=false"]
    healthcheck:
      test: ["CMD-SHELL", "auditbeat test config || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      mode: global
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

networks:
  elastic:
    external: true

volumes:
  auditbeat:

configs:
  ab_config:
    file: $PWD/elk/beats/auditbeat/config/auditbeat.yml
